### ISSUE TITLE
Is there a specific reason why you choose an web api ever the wix node_module?

### ISSUE THREAD

**Issue by Jupiterrr** [siddharthkp/atom-import-cost#2]
In the readme of the original project from wix:
> Import Cost [Node module](https://github.com/wix/import-cost/tree/master/packages/import-cost) - use freely to implement extensions for other IDE (or contribute them to this repository)

Is there a specific reason why you choose the web api over this module?

**Comment by siddharthkp** [comment]
They hadn't pulled that out when I started :)

Would be happy to reuse, would you like to give a pull request?
