### ISSUE TITLE
v0.8.5 are not available at Atom packages

### ISSUE THREAD

**Issue by Julian-B90** [siddharthkp/atom-import-cost#6]
At the atom packages site the last version ist v0.8.4

https://atom.io/packages/atom-import-cost

<img width="604" alt="bildschirmfoto 2017-08-17 um 10 24 15" src="https://user-images.githubusercontent.com/4377396/29402724-4d7755e8-8336-11e7-8448-44fcccd669cf.png">

**Comment by siddharthkp** [comment]
Just published 0.9.0!
