### ISSUE TITLE
Value of the size of the overlay over tabs

### ISSUE THREAD

**Issue by dmitrymalakhov** [siddharthkp/atom-import-cost#8]
![screenshot from 2017-08-24 00-02-26](https://user-images.githubusercontent.com/2477267/29650796-c9e3683c-88a5-11e7-83be-83056f63377e.png)

problem appears while scrolling

Atom 1.18.0

**Comment by siddharthkp** [comment]
Whoops!

Do you want to take a shot at it?

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/atom-import-cost/pull/11#issuecomment-336575712
